#!/usr/bin/env python

import os
import sys

import rospkg
r = rospkg.RosPack()
p = r.get_path('qt_gui')
sys.path.append(os.path.join(p, 'src'))

from qt_gui.main import Main
main = Main(p, invoked_filename=os.path.abspath(__file__))
# TODO add dummy plugin provider 
sys.exit(main.main())
