#!/usr/bin/env python3

import os
import sys

from ament_index_python.resources import get_resource
from qt_gui.main import Main

_, qtgui_path = get_resource('packages', 'qt_gui')
main = Main(qtgui_path, invoked_filename=os.path.abspath(__file__))
# TODO add dummy plugin provider
sys.exit(main.main())
